
### ========= Get User =========
GET http://localhost:5001/users

### ========= Creat Users =========
POST http://localhost:5001/users/signup
Content-Type: application/json

{
  "id": "1",
  "name": "user123",
  "email": "test@test.c",
  "password": "12345678"
}


#### Get users by id

GET http://localhost:5001/users/2