
### ========= Get All Users =========
GET http://localhost:5001/users



### ========= Creat Users =========
POST http://localhost:5001/users/signup
Content-Type: application/json

{
  "id": "4",
  "name": "clari",
  "email": "clair@hms.com",
  "password": "1234567890"
}


#### Get users by id

GET http://localhost:5001/users/4
